//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thongke
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public int MASV { get; set; }
        public string MAMH { get; set; }
        public string DIEM { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
    }
}
